version: "3.3"

services:
  terrier-base:
    build: ./Docker
    ports:
    - 80:3000
  environment:
    - MONGO_URI=mongodb://sampledb/sample
  networks:
    - terriernet    




networks:
  terriernet:
    driver: bridge    